"""empty message

Revision ID: 4c7c79ed016d
Revises: cacf03cb26d6
Create Date: 2022-02-10 22:37:32.252437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7c79ed016d'
down_revision = 'cacf03cb26d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokeparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('hp', sa.String(length=50), nullable=True),
    sa.Column('defense', sa.String(length=50), nullable=True),
    sa.Column('attack', sa.String(length=50), nullable=True),
    sa.Column('ability_1', sa.String(length=50), nullable=True),
    sa.Column('sprite', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('poke_user_join',
    sa.Column('pokeparty_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokeparty_id'], ['pokeparty.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pokeparty_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poke_user_join')
    op.drop_table('pokeparty')
    # ### end Alembic commands ###
